# Generated by Django 5.0.6 on 2024-06-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_remove_landlord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
