# Generated by Django 5.0.6 on 2024-06-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
    ]
