# Generated by Django 5.0.6 on 2024-06-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('properties', '0003_remove_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property'),
        ),
    ]
