# Generated by Django 5.0.6 on 2024-09-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("accreditation_number", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("cell_number", models.CharField(max_length=20)),
                ("street_address", models.CharField(max_length=255)),
                ("nearest_campus", models.CharField(max_length=255)),
                ("residence_name", models.CharField(max_length=255)),
                ("university", models.CharField(max_length=50)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=255, null=True)),
                ("map_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "directions_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "streetview_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "Accommodations",
            },
        ),
    ]
